/*
 * GENERATED by tools/pokerogue/import-searchdex.cjs from the PokeRogue
 * SearchDex (https://github.com/sandstormer/pokerogue-dex). Do not edit
 * by hand; re-run the importer to update.
 */

export const Items: import('../../../sim/dex-items').ModdedItemDataTable = {
	maxmushrooms: {
		name: "Max Mushrooms",
		spritenum: 0,
		num: 2000,
		gen: 8,
		desc: "If held by a Pokemon with a Gigantamax form, it can Gigantamax like a Mega Evolution.",
		shortDesc: "Lets a Pokemon with a Gigantamax form Gigantamax (like a Mega Evolution).",
		megaStone: {
			"Venusaur": "Venusaur-Gmax",
			"Charizard": "Charizard-Gmax",
			"Blastoise": "Blastoise-Gmax",
			"Butterfree": "Butterfree-Gmax",
			"Pikachu": "Pikachu-Gmax",
			"Meowth": "Meowth-Gmax",
			"Machamp": "Machamp-Gmax",
			"Gengar": "Gengar-Gmax",
			"Kingler": "Kingler-Gmax",
			"Lapras": "Lapras-Gmax",
			"Eevee": "Eevee-Gmax",
			"Snorlax": "Snorlax-Gmax",
			"Garbodor": "Garbodor-Gmax",
			"Melmetal": "Melmetal-Gmax",
			"Rillaboom": "Rillaboom-Gmax",
			"Cinderace": "Cinderace-Gmax",
			"Inteleon": "Inteleon-Gmax",
			"Corviknight": "Corviknight-Gmax",
			"Orbeetle": "Orbeetle-Gmax",
			"Drednaw": "Drednaw-Gmax",
			"Coalossal": "Coalossal-Gmax",
			"Flapple": "Flapple-Gmax",
			"Appletun": "Appletun-Gmax",
			"Sandaconda": "Sandaconda-Gmax",
			"Toxtricity": "Toxtricity-Gmax",
			"Centiskorch": "Centiskorch-Gmax",
			"Hatterene": "Hatterene-Gmax",
			"Grimmsnarl": "Grimmsnarl-Gmax",
			"Alcremie": "Alcremie-Gmax",
			"Copperajah": "Copperajah-Gmax",
			"Duraludon": "Duraludon-Gmax",
			"Urshifu": "Urshifu-Gmax",
			"Urshifu-Rapid-Strike": "Urshifu-Rapid-Strike-Gmax",
			"Toxtricity-Low-Key": "Toxtricity-Low-Key-Gmax"
		},
		itemUser: [
			"Venusaur",
			"Charizard",
			"Blastoise",
			"Butterfree",
			"Pikachu",
			"Meowth",
			"Machamp",
			"Gengar",
			"Kingler",
			"Lapras",
			"Eevee",
			"Snorlax",
			"Garbodor",
			"Melmetal",
			"Rillaboom",
			"Cinderace",
			"Inteleon",
			"Corviknight",
			"Orbeetle",
			"Drednaw",
			"Coalossal",
			"Flapple",
			"Appletun",
			"Sandaconda",
			"Toxtricity",
			"Centiskorch",
			"Hatterene",
			"Grimmsnarl",
			"Alcremie",
			"Copperajah",
			"Duraludon",
			"Urshifu",
			"Urshifu-Rapid-Strike",
			"Toxtricity-Low-Key"
		],
		// Like a Mega Stone, it can't be removed from a Pokemon that can use it
		// (before or after Gigantamaxing).
		onTakeItem(item, source) {
			if (!source || !item.megaStone) return true;
			const line = source.baseSpecies.baseSpecies;
			return !Object.keys(item.megaStone).some(name => this.dex.species.get(name).baseSpecies === line);
		},
	},
};
