/*
 * GENERATED by tools/pokerogue/import-searchdex.cjs from the PokeRogue
 * SearchDex (https://github.com/sandstormer/pokerogue-dex). Do not edit
 * by hand; re-run the importer to update.
 */

export const Pokedex: import('../../../sim/dex-species').ModdedSpeciesDataTable = {
	"venusaurgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 120,
			"atk": 122,
			"def": 90,
			"spa": 108,
			"spd": 105,
			"spe": 80
		},
		"abilities": {
			"0": "Effect Spore"
		},
		"types": [
			"Grass",
			"Poison"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Venusaur"
	},
	"charizardgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 118,
			"atk": 99,
			"def": 88,
			"spa": 134,
			"spd": 95,
			"spe": 100
		},
		"abilities": {
			"0": "Berserk"
		},
		"types": [
			"Fire",
			"Flying"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Charizard"
	},
	"blastoisegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 119,
			"atk": 108,
			"def": 125,
			"spa": 105,
			"spd": 110,
			"spe": 63
		},
		"abilities": {
			"0": "Shell Armor"
		},
		"types": [
			"Water",
			"Steel"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Blastoise"
	},
	"butterfreegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 80,
			"atk": 40,
			"def": 75,
			"spa": 120,
			"spd": 95,
			"spe": 85
		},
		"abilities": {
			"0": "Compound Eyes"
		},
		"types": [
			"Bug",
			"Flying"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Butterfree"
	},
	"pikachucosplay": {
		"inherit": true,
		"baseStats": {
			"hp": 45,
			"atk": 80,
			"def": 50,
			"spa": 75,
			"spd": 60,
			"spe": 120
		},
		"abilities": {
			"0": "Static",
			"H": "Lightning Rod"
		}
	},
	"pikachurockstar": {
		"inherit": true,
		"baseStats": {
			"hp": 45,
			"atk": 80,
			"def": 50,
			"spa": 75,
			"spd": 60,
			"spe": 120
		},
		"abilities": {
			"0": "Static",
			"H": "Lightning Rod"
		}
	},
	"pikachubelle": {
		"inherit": true,
		"baseStats": {
			"hp": 45,
			"atk": 80,
			"def": 50,
			"spa": 75,
			"spd": 60,
			"spe": 120
		},
		"abilities": {
			"0": "Static",
			"H": "Lightning Rod"
		}
	},
	"pikachupopstar": {
		"inherit": true,
		"baseStats": {
			"hp": 45,
			"atk": 80,
			"def": 50,
			"spa": 75,
			"spd": 60,
			"spe": 120
		},
		"abilities": {
			"0": "Static",
			"H": "Lightning Rod"
		}
	},
	"pikachuphd": {
		"inherit": true,
		"baseStats": {
			"hp": 45,
			"atk": 80,
			"def": 50,
			"spa": 75,
			"spd": 60,
			"spe": 120
		},
		"abilities": {
			"0": "Static",
			"H": "Lightning Rod"
		}
	},
	"pikachulibre": {
		"inherit": true,
		"baseStats": {
			"hp": 45,
			"atk": 80,
			"def": 50,
			"spa": 75,
			"spd": 60,
			"spe": 120
		},
		"abilities": {
			"0": "Static",
			"H": "Lightning Rod"
		}
	},
	"pikachugmax": {
		"inherit": true,
		"baseStats": {
			"hp": 125,
			"atk": 95,
			"def": 60,
			"spa": 90,
			"spd": 70,
			"spe": 90
		},
		"abilities": {
			"0": "Lightning Rod"
		},
		"types": [
			"Electric"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Pikachu"
	},
	"meowthgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 115,
			"atk": 110,
			"def": 65,
			"spa": 65,
			"spd": 70,
			"spe": 115
		},
		"abilities": {
			"0": "Technician"
		},
		"types": [
			"Normal"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Meowth"
	},
	"machampgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 120,
			"atk": 170,
			"def": 95,
			"spa": 80,
			"spd": 85,
			"spe": 55
		},
		"abilities": {
			"0": "Guts"
		},
		"types": [
			"Fighting"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Machamp"
	},
	"gengargmax": {
		"inherit": true,
		"baseStats": {
			"hp": 150,
			"atk": 50,
			"def": 65,
			"spa": 150,
			"spd": 85,
			"spe": 100
		},
		"abilities": {
			"0": "Shadow Tag"
		},
		"types": [
			"Ghost",
			"Poison"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Gengar"
	},
	"kinglergmax": {
		"inherit": true,
		"baseStats": {
			"hp": 92,
			"atk": 145,
			"def": 140,
			"spa": 60,
			"spd": 65,
			"spe": 73
		},
		"abilities": {
			"0": "Tough Claws"
		},
		"types": [
			"Water"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Kingler"
	},
	"laprasgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 170,
			"atk": 97,
			"def": 85,
			"spa": 107,
			"spd": 111,
			"spe": 65
		},
		"abilities": {
			"0": "Shield Dust"
		},
		"types": [
			"Water",
			"Ice"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Lapras"
	},
	"eeveegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 110,
			"atk": 95,
			"def": 70,
			"spa": 90,
			"spd": 85,
			"spe": 85
		},
		"abilities": {
			"0": "Protean"
		},
		"types": [
			"Normal"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Eevee"
	},
	"snorlaxgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 210,
			"atk": 130,
			"def": 65,
			"spa": 85,
			"spd": 120,
			"spe": 30
		},
		"abilities": {
			"0": "Harvest"
		},
		"types": [
			"Normal"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Snorlax"
	},
	"pichuspikyeared": {
		"inherit": true,
		"abilities": {
			"0": "Static",
			"H": "Lightning Rod"
		}
	},
	"slakoth": {
		"inherit": true,
		"abilities": {
			"0": "Truant",
			"H": "Stall"
		}
	},
	"vigoroth": {
		"inherit": true,
		"abilities": {
			"0": "Vital Spirit",
			"H": "Insomnia"
		}
	},
	"slaking": {
		"inherit": true,
		"abilities": {
			"0": "Truant",
			"H": "Stall"
		}
	},
	"absolmegaz": {
		"inherit": true,
		"abilities": {
			"0": "Super Luck"
		}
	},
	"garchompmegaz": {
		"inherit": true,
		"abilities": {
			"0": "Rough Skin"
		}
	},
	"lucariomegaz": {
		"inherit": true,
		"abilities": {
			"0": "Inner Focus"
		}
	},
	"heatranmega": {
		"inherit": true,
		"abilities": {
			"0": "Flash Fire"
		}
	},
	"regigigas": {
		"inherit": true,
		"abilities": {
			"0": "Slow Start",
			"H": "Normalize"
		}
	},
	"audinomega": {
		"inherit": true,
		"abilities": {
			"0": "Regenerator"
		}
	},
	"darmanitanzen": {
		"inherit": true,
		"abilities": {
			"0": "Sheer Force",
			"H": "Zen Mode"
		}
	},
	"archen": {
		"inherit": true,
		"abilities": {
			"0": "Defeatist",
			"H": "Wimp Out"
		}
	},
	"archeops": {
		"inherit": true,
		"abilities": {
			"0": "Defeatist",
			"H": "Emergency Exit"
		}
	},
	"garbodorgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 115,
			"atk": 121,
			"def": 102,
			"spa": 81,
			"spd": 102,
			"spe": 53
		},
		"abilities": {
			"0": "Toxic Debris"
		},
		"types": [
			"Poison",
			"Steel"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Garbodor"
	},
	"ferroseed": {
		"inherit": true,
		"abilities": {
			"0": "Iron Barbs",
			"H": "Anticipation"
		}
	},
	"wimpod": {
		"inherit": true,
		"abilities": {
			"0": "Wimp Out",
			"H": "Run Away"
		}
	},
	"golisopod": {
		"inherit": true,
		"abilities": {
			"0": "Emergency Exit",
			"H": "Anticipation"
		}
	},
	"golisopodmega": {
		"inherit": true,
		"abilities": {
			"0": "Shell Armor"
		}
	},
	"melmetalgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 161,
			"atk": 169,
			"def": 154,
			"spa": 106,
			"spd": 76,
			"spe": 34
		},
		"abilities": {
			"0": "Iron Fist"
		},
		"types": [
			"Steel"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Melmetal"
	},
	"rillaboomgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 125,
			"atk": 140,
			"def": 105,
			"spa": 90,
			"spd": 85,
			"spe": 85
		},
		"abilities": {
			"0": "Grassy Surge"
		},
		"types": [
			"Grass"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Rillaboom"
	},
	"cinderacegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 100,
			"atk": 141,
			"def": 80,
			"spa": 95,
			"spd": 80,
			"spe": 134
		},
		"abilities": {
			"0": "Libero"
		},
		"types": [
			"Fire"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Cinderace"
	},
	"inteleongmax": {
		"inherit": true,
		"baseStats": {
			"hp": 95,
			"atk": 117,
			"def": 67,
			"spa": 147,
			"spd": 67,
			"spe": 137
		},
		"abilities": {
			"0": "Sniper"
		},
		"types": [
			"Water"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Inteleon"
	},
	"corviknightgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 118,
			"atk": 112,
			"def": 135,
			"spa": 63,
			"spd": 90,
			"spe": 77
		},
		"abilities": {
			"0": "Mirror Armor"
		},
		"types": [
			"Flying",
			"Steel"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Corviknight"
	},
	"orbeetlegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 75,
			"atk": 50,
			"def": 140,
			"spa": 100,
			"spd": 150,
			"spe": 90
		},
		"abilities": {
			"0": "Trace"
		},
		"types": [
			"Bug",
			"Psychic"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Orbeetle"
	},
	"drednawgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 115,
			"atk": 137,
			"def": 115,
			"spa": 61,
			"spd": 83,
			"spe": 74
		},
		"abilities": {
			"0": "Strong Jaw"
		},
		"types": [
			"Water",
			"Rock"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Drednaw"
	},
	"coalossalgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 140,
			"atk": 100,
			"def": 132,
			"spa": 95,
			"spd": 100,
			"spe": 43
		},
		"abilities": {
			"0": "Steam Engine"
		},
		"types": [
			"Rock",
			"Fire"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Coalossal"
	},
	"flapplegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 100,
			"atk": 125,
			"def": 90,
			"spa": 105,
			"spd": 70,
			"spe": 95
		},
		"abilities": {
			"0": "Hustle"
		},
		"types": [
			"Grass",
			"Dragon"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Flapple"
	},
	"appletungmax": {
		"inherit": true,
		"baseStats": {
			"hp": 150,
			"atk": 100,
			"def": 95,
			"spa": 115,
			"spd": 95,
			"spe": 30
		},
		"abilities": {
			"0": "Thick Fat"
		},
		"types": [
			"Grass",
			"Dragon"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Appletun"
	},
	"sandacondagmax": {
		"inherit": true,
		"baseStats": {
			"hp": 102,
			"atk": 137,
			"def": 140,
			"spa": 70,
			"spd": 80,
			"spe": 81
		},
		"abilities": {
			"0": "Sand Spit"
		},
		"types": [
			"Ground"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Sandaconda"
	},
	"toxtricitygmax": {
		"inherit": true,
		"baseStats": {
			"hp": 114,
			"atk": 105,
			"def": 82,
			"spa": 137,
			"spd": 82,
			"spe": 82
		},
		"abilities": {
			"0": "Punk Rock"
		},
		"types": [
			"Electric",
			"Poison"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Toxtricity"
	},
	"centiskorchgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 130,
			"atk": 125,
			"def": 75,
			"spa": 94,
			"spd": 100,
			"spe": 101
		},
		"abilities": {
			"0": "Flash Fire"
		},
		"types": [
			"Fire",
			"Bug"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Centiskorch"
	},
	"hatterenegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 87,
			"atk": 100,
			"def": 110,
			"spa": 146,
			"spd": 118,
			"spe": 49
		},
		"abilities": {
			"0": "Magic Bounce"
		},
		"types": [
			"Psychic",
			"Fairy"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Hatterene"
	},
	"grimmsnarlgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 130,
			"atk": 138,
			"def": 75,
			"spa": 110,
			"spd": 92,
			"spe": 65
		},
		"abilities": {
			"0": "Prankster"
		},
		"types": [
			"Dark",
			"Fairy"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Grimmsnarl"
	},
	"alcremiegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 105,
			"atk": 70,
			"def": 85,
			"spa": 130,
			"spd": 141,
			"spe": 64
		},
		"abilities": {
			"0": "Misty Surge"
		},
		"types": [
			"Fairy"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Alcremie"
	},
	"copperajahgmax": {
		"inherit": true,
		"baseStats": {
			"hp": 177,
			"atk": 155,
			"def": 79,
			"spa": 90,
			"spd": 79,
			"spe": 20
		},
		"abilities": {
			"0": "Mold Breaker"
		},
		"types": [
			"Steel",
			"Ground"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Copperajah"
	},
	"duraludongmax": {
		"inherit": true,
		"baseStats": {
			"hp": 100,
			"atk": 120,
			"def": 110,
			"spa": 160,
			"spd": 85,
			"spe": 60
		},
		"abilities": {
			"0": "Analytic"
		},
		"types": [
			"Steel",
			"Dragon"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Duraludon"
	},
	"urshifugmax": {
		"inherit": true,
		"baseStats": {
			"hp": 120,
			"atk": 150,
			"def": 115,
			"spa": 83,
			"spd": 75,
			"spe": 107
		},
		"abilities": {
			"0": "Unseen Fist"
		},
		"types": [
			"Fighting",
			"Dark"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Urshifu"
	},
	"urshifurapidstrikegmax": {
		"inherit": true,
		"baseStats": {
			"hp": 120,
			"atk": 150,
			"def": 115,
			"spa": 83,
			"spd": 75,
			"spe": 107
		},
		"abilities": {
			"0": "Unseen Fist"
		},
		"types": [
			"Fighting",
			"Water"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Urshifu-Rapid-Strike"
	},
	"tatsugiricurlymega": {
		"inherit": true,
		"abilities": {
			"0": "Storm Drain"
		}
	},
	"tatsugiridroopymega": {
		"inherit": true,
		"abilities": {
			"0": "Storm Drain"
		}
	},
	"tatsugiristretchymega": {
		"inherit": true,
		"abilities": {
			"0": "Storm Drain"
		}
	},
	"darmanitangalarzen": {
		"inherit": true,
		"abilities": {
			"0": "Gorilla Tactics",
			"H": "Zen Mode"
		}
	},
	"toxtricitylowkeygmax": {
		"inherit": true,
		"baseStats": {
			"hp": 114,
			"atk": 105,
			"def": 82,
			"spa": 137,
			"spd": 82,
			"spe": 82
		},
		"abilities": {
			"0": "Punk Rock"
		},
		"types": [
			"Electric",
			"Poison"
		],
		"requiredItem": "Max Mushrooms",
		"battleOnly": "Toxtricity-Low-Key"
	}
};
